baseURL = 'https://azabelmena.xyz'
languageCode = 'en-us'
title = ""
copyright = 'Alec S. Zabel-Mena'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 70
  [[menu.main]]
    identifier = "research_interests"
    name       = "Research Interests"
    url        = "/research_interests/"
    weight     = 60
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/notes/"
    weight     = 50
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "https://cv.azabelmena.xyz"
    weight     = 30
  [[menu.main]]
    identifier = "zibaldone"
    name       = "Zibaldone"
    url        = "https://zibaldone.azabelmena.xyz"
    weight     = 20
  [[menu.main]]
    identifier = "zettelkasten"
    name       = "Zettelkasten"
    url        = "https://zettelkasten.azabelmena.xyz"
    weight     = 10

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]']]
                    inline = [['\(', '\)']]


[params]
  math=true
  dateFormat = ':date_long'

  showGraph = false

  [params.author]
    name = 'Alec S. Zabel-Mena'
    email = 'alec.zabel@upr.edu'

  [params.home]
    showRecentPosts = false

    recentPostsLimit = 0

  [params.notes]
    pageSize = 20

    showCategoryFilter = true

  [params.footer]
    creativeCommonsLicense = 'by_nc'

    showCreativeCommonsIcons = true

    showThemeCredit = true

  [params.robotstxt]
    blockCC = true

    blockAI = true
